### ISSUE TITLE
我的AD Mod出蚆蛒（Bug）了，快来修

### ISSUE THREAD

**Issue by antimatter19728** [QwQe308/AD-Space-Mod#2]
[原issue](https://github.com/Antimatter-Dimensions-Modding-Community/Antimatter19728-AD-Mods/issues/3)
**描述蚆蛒**
游戏在解锁Pelle后崩溃

**如何复现**
复现方法:
1. 购买所有现实/虚幻升级
2. 进入Celestial菜单，Pelle子菜单

**Expected behavior**
游戏会崩溃

**Screenshots**
![1](https://github.com/user-attachments/assets/d0a41da5-ab23-493a-8161-4e5fb15196c1)
![2](https://github.com/user-attachments/assets/dcfacb44-9a01-4068-b06e-5eb03e0095d9)
![3](https://github.com/user-attachments/assets/4ed1900a-1005-41a3-93cd-409bcf03cb5c)

**Additional context**
[出现蚆蛒的Vue组件](https://github.com/Antimatter-Dimensions-Modding-Community/Antimatter19728-AD-Mods/blob/main/ng-plus/src/components/tabs/celestial-pelle/PelleTab.vue)

**Comment by antimatter19728** [comment]
@WYXkk @QwQe308

**Comment by QwQe308** [comment]
Why should i, i dont even know who you are
No unrelated reports plz, ask in currect ways.
